### ISSUE TITLE
intuitive drop x,y 

### ISSUE THREAD

**Issue by zahachtah** [isaacHagoel/svelte-dnd-action#105]
I noticed that it seems the location at which svelte-dnd-actions wants to drop things you move is based on the middle of the div you are moving? Once I figured that out it was relatively easy to get it to drop where you want. 

But would the location of the cursor be intuitively better? Most test examples you use seem to have one row items and thus the difference is not an issue, but when you dragged item is fairly large it is much harder to estimate where the middle is and thus where the drop will be placed.

Seems simple and quick to test/review if this would be a UI improvement or not? just a suggestion

**Comment by isaacHagoel** [comment]
Hi,
I think that in most cases, the UX is much better when using the 'centre of gravity' rather than the mouse position. 
I gained this insight by reading [this article](https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b) if I remember correctly.
I agree that for large objects it doesn't feel quite right (not sure whether mouse cursor will feel better). Maybe it can be a configurable thing (as in one of the parameters that are passed into the dndzone)

**Comment by zahachtah** [comment]
Very interesting article! And I see the point. 

possibly a different perspective is when dnd has to work together with inducing scroll while moving. I think (but I might be wrong) that the point that induces the scroll is based on the mouse position. that could add confusion if scroll behavior is induced differently than the reordering behavior over the items. 

This is not any crucial thing at all and I just bring it out of interest in this framework. Possibly one could move the item one picks up so that the center of gravity corresponds to the mouse position visually while moving? then all issues mentioned resolve.

Anyhow, I don't think this is an issue really, more thought and suggestion. Feel free to close if you think it's good as is.

**Comment by zahachtah** [comment]
oh, and reading further, the react version has keyboard support :-)

**Comment by isaacHagoel** [comment]
You are welcome to experiment with these ideas and see if u can find something that feels better. It feels okay to me but better is always possible I think.
And yeah, the React library supports tons of stuff and have evolved over a long period of time. My goal is to only support features that are backed by real use cases. With time, we might also have keyboard support (and maybe not :))

**Comment by zahachtah** [comment]
I have implemented it in the site I use and have to agree that the physical approach made more sense than the mouse location. I may add a little indicator at the middle of the moving component to make that clearer. 

2 quick questions: 

1) when dragDisabled=false, does it still attach all functions to elements but just doesn't fire them, or does in just not build the "action" for that element?

2) is there an easy way to have drag/copy, i.e. say I hold the 'cmd' key while dragging it will not remove the item but instead make a copy you can drop in another container?

**Comment by isaacHagoel** [comment]
1. it registers the elements but does not attach the listeners. See line 377 in action.js.
```javascript
 if (!dragDisabled) {
                dragHandle.addEventListener('mousedown', handleMouseDown);
                dragHandle.addEventListener('touchstart', handleMouseDown);
...
```
2. Currently no. I would think that cloning elements could be done using a button rather than using drag would be better UX. If we did want to add such capability, first we would need to define its exact behaviour (what happens if I let go of cmd while dragging? how is the new id created? how is the item marked as a copy? what if you drop the copy back into the container u dragged it from? etc). After that we could discuss potential ways to achieve it.

**Comment by isaacHagoel** [comment]
related to #109

**Comment by isaacHagoel** [comment]
closing this for now as #109 covers copy via drag

**Comment by isaacHagoel** [comment]
> oh, and reading further, the react version has keyboard support :-)

well, we have keyboard support too now 😄
