### ISSUE TITLE
Draggable is jumping when first entering the dropzone. Question on shadow elements.

### ISSUE THREAD

**Issue by MaddoxDevelopment** [isaacHagoel/svelte-dnd-action#106]
Great library, thanks for making it.

For some reason, when I drag my element from one zone to another zone, it jumps back to the left side, do you know what might be causing this issue? 

The height of both drop-zones are 100vh.

Example Video: https://streamable.com/bm0sue

Also, is there a way to change the HTML of the element being dragged? I would like to transform it to look like the input that is going to be rendered, but cannot figure out a good way to intercept that. 

Thanks!

**Comment by isaacHagoel** [comment]
Hi,
This is actually the intended behaviour. If you add a border around the element it might make more visual sense.
The dragged element morphs to match its new shape in the container underneath (which is much larger in your case). It morphs around the mouse pointer such that the pointer maintains its relative position within the element (ex: if it was next to the top left corner before morphing it would stay there after morphing). 
Not doing so, can cause the pointer to end up outside of the new shape.

The code responsible for the morphing (and maintaining the pointer position) is [here](https://github.com/isaacHagoel/svelte-dnd-action/blob/2b0983743a3ba26e20708d258dfcae33192af168/src/helpers/styler.js#L52).
You can see which computed styles are copied and which ones aren't. 

In order to make it look like the input additional styles would need to be copied (and it might need to be an input element to begin with).

**Comment by MaddoxDevelopment** [comment]
Oh i see, I added a border to the dragged element and it makes much more sense visually, i'll figure out a way to style it then. Thanks for your help!

**Comment by MaddoxDevelopment** [comment]
Re-opening this for a further request.

I pulled the repo to try out a few things and figured out I can solve all of my issues by having access to the inner html that is being set on the dragged element in the morph function. Would this be something you'd be willing to expose via the api? Possibly some sort of configuration to allow us to pass markup that the morphed element gets turned into when it gets picked up.

<img width="1226" alt="Screen Shot 2020-08-18 at 7 34 52 PM" src="https://user-images.githubusercontent.com/11528924/90578842-e8c1b700-e189-11ea-955a-c4c7673ea7ae.png">

Just changed the bottom line there and it works great. https://streamable.com/7xonif

@isaacHagoel

**Comment by isaacHagoel** [comment]
Thanks for the PR. I will have a look at it and test hopefully today (if not then tomorrow for sure). 
Yeah, I'm totally open to this.
