### ISSUE TITLE
[Feature Request] Allow an element to be copied from one drop zone to another.

### ISSUE THREAD

**Issue by MaddoxDevelopment** [isaacHagoel/svelte-dnd-action#109]
Is it in the scope to add the ability to drag an element from the drop zone, but not have it remove the original element? Essentially copying it. Similar to https://bevacqua.github.io/dragula/ Dragula's copy feature.

**Comment by isaacHagoel** [comment]
It can be in scope. The implementation should probably be quite different to Dragula's. 
This library never manipulates the lists directly, it lets the consider/finalize handlers do it.
Looks like we could achieve dragula like copy with a relatively small number of changes.  This is just off the top of my head but one way of doing it would be to add an option like
`copyOnDragStart`
when it is set to true: 
- dragStart from the list won't remove the item.
- draggedEntered/ draggedOverIndex/ dragLeft should be ignored if they fire on the origin list
- dropping outside of any list should be addressed (still animated but not update the items)

On issue that will arise is when someone copies an element, drop it in another list and then drag it back to the original list (dragula seems to allow it). This will result in `id` conflict unless addressed.

**Comment by MaddoxDevelopment** [comment]
My first thought would be that if i dragged it back to the original list and an item with that id already exists, it would just do nothing.

**Comment by isaacHagoel** [comment]
Hi @MaddoxDevelopment and @zahachtah,
I have implemented a feature that can enable copy on drag as well as a whole range of other "advanced" capabilities. 
The idea is to expose more information in the dispatched events so that the consuming component could make a wider range of decisions in the `consider` and `finalize` handlers. 
There are two examples in the [pull request](https://github.com/isaacHagoel/svelte-dnd-action/pull/114) that demonstrate how to achieve dragula like copy on drag or a simpler version, that allows copying to the same container.

Would be awesome if you could take a look and share your opinion. Will this kind of solution satisfy your needs?

Feel free to check-out [the branch](https://github.com/isaacHagoel/svelte-dnd-action/tree/109-enable-copy-on-drag) and try it yourselves.
Ideally, I will get your feedback before merging.
Thanks,
Isaac

**Comment by isaacHagoel** [comment]
I merged the PR so instead of the branch you can try it with the master branch if you'd like. I figured I would like to have this info available whether i later add a specific implementation for copy later or not.

**Comment by zahachtah** [comment]
The coming week is crazy as I just came home from one year abroad and will sell my house. hopefully, I'll get to it then.

**Comment by isaacHagoel** [comment]
@zahachtah sounds like exciting times! good luck!

**Comment by zahachtah** [comment]
playing a bit with this now, using the pull request examples you linked to above. Testing to drag it into a second dndzone. not entirely sure what goes wrong here, I suspect the handle function doesn't get the right info, no? I just want to check if I can copy-drag from one zone into another.

https://svelte.dev/repl/3baed168f17b4351a73d90c484258fdf?version=3.25.0

question: in the handler functions the e.details.items, does that link directly to the item-array assigned by use:dndzone={{items}} ? I am trying to make the handler function generic for either dndzone....

**Comment by isaacHagoel** [comment]
Hi @zahachtah 
See a working example [in this REPL that I also added to the "examples" section of the README](https://svelte.dev/repl/924b4cc920524065a637fa910fe10193?version=3.25.1). 
In your REPL there are a few issues. You are passing items1 and items2 into the dndzone as a shorthand (instead of `{items:items1, flipDurationMs}}`). Your handlers update a variable called `items` instead of `items1` or `items2`.

In order to make the handler generic you probably need to tell it which zone it is dealing with (you could look at the "Board" example to see how the handler works with any column)

**Comment by MaddoxDevelopment** [comment]
Looks awesome, thanks for adding this.

**Comment by zahachtah** [comment]
Many thanks for that! this is perfect!
