### ISSUE TITLE
The handleDndFinalizeCards function fires twice;

### ISSUE THREAD

**Issue by blazzjosh** [isaacHagoel/svelte-dnd-action#121]
Hello Gents,

Using the boards example, I notice that The handleDndFinalizeCards function fires twice;
Please drag a card and see the console
How can this be fixed?

REPL with Error:
https://svelte.dev/repl/01e391a3622341cda107dcf8b3960785?version=3.22.2

Thanks

**Comment by isaacHagoel** [comment]
Hi,
the event is not fired twice on the same zone. it is fired on the destination zone (to tell it the item belongs there now) and on the origin zone (to tell it that the item does not belong there anymore).
Your log message is a bit misleading (because it implies that the item has "landed").
If you change it and add a printout of the info it will make things clearer. Something like:
```javascript
console.log("got finalize event for column" + cid, e.detail.info);
```

**Comment by blazzjosh** [comment]
Ohh clearer....
How would i get the zone's columnId where the item is dropped into?

**Comment by isaacHagoel** [comment]
Please see the board in [this REPL](https://svelte.dev/repl/521ab5b44ff544a9ba3f043fbc425e2b?version=3.22.2)

**Comment by blazzjosh** [comment]
👍. many thanks for the verbose....
Great Library!!
