### ISSUE TITLE
component redraws the dragged item

### ISSUE THREAD

**Issue by hbbio** [isaacHagoel/svelte-dnd-action#135]
While playing with dnd, I seems that the dragged component is redrawn. Cf. [REPL example](https://svelte.dev/repl/5e53599e7843479aa4772045f81255df?version=3).

Is there a way to prevent that?

**Comment by isaacHagoel** [comment]
what do you mean redrawn? can you please elaborate?
 the REPL looks normal to me (given that you don't need/want animations).

**Comment by isaacHagoel** [comment]
do u mean the black border (focus)?

**Comment by isaacHagoel** [comment]
@hbbio I fixed the outline issue. check out version 0.6.2 (your REPL should get the latest version when u do a hard refresh).
if this is is not the issue you were referring to feel free to re-open and add details. 
Thanks

**Comment by hbbio** [comment]
Thanks @isaacHagoel for the quick answer but sorry for not being descriptive enough...

What happens is the dragged item triggers a new component redraw. You can see it from the log in the console when dragging an item. I added a "contenteditable" to show why it may matter (in addition to performance): Try to edit the label of a item and then drag it. On release, the original component is drawn (without the modifications).

**Comment by isaacHagoel** [comment]
Hi @hbbio ,
The contenteditable in your example is not bound to anything Svelte knows about. That's why it is not persisted. it is not related to the library. Any state change will cause that.
I fixed it in [this copy of your REPL](https://svelte.dev/repl/0dfd5e6c101f481c9fb64f5dd9475fa9?version=3.29.0).
contenteditable in Svelte is explained [here](https://svelte.dev/tutorial/contenteditable-bindings).

As for the original issue: when drag starts, the item is first taken out of the original list. 
The reason is that depending on the velocity of the drag and  the layout of the container relative other adjacent or nested containers, the item might immediately find itself hovering over another container. The assumption that it will stay over the origin zone is not a valid one. One way or the other, the placeholder element needs to be inserted to the list instead of the original one.
I don't see any issue with it, performance or otherwise but am totally open to be convinced to the contrary.

**Comment by hbbio** [comment]
Thanks for the explanation, it makes sense. However, in my case the components come from a separate library (which uses contenteditable underneath) and I am not able to sync the state immediately. 

The less featureful `svelte-sortable-list` does not trigger a redraw so I'll keep it for now cf. https://svelte.dev/repl/ee53c4a305d1488486447e9dcd72698e?version=3.29.0

**Comment by isaacHagoel** [comment]
Sorry sir. If you show me an example with the library u are using that has contenteditable, I might be able to help.
As the json.stringify in your example shows, editing the content has no affect on the actual data that your app knowns about, the event that is emitted doesn't have the edits either. The changes seem to be purely visual. I have to wonder what meaning these changes have if they are not persisted anywhere.

Unlike svelte-sortable-list, this library is not responsible for rendering your items (it is not a higher order component), it is your component that does the rendering and everything plays by normal Svelte rules (== svelte renders the data it knows about). 

With that said, I think `svelte-sortable-list` is great and if it fits your use-case better you should totally stick to it. Thanks for giving svelte-dnd-action a shot.

**Comment by hbbio** [comment]
Thanks again for your support! The lib I'm using is quite huge and emits updates periodically but it is too costly to update the state at each keypress from `bind:innerHTML` (plus there are some quirks with Svelte + complex contenteditable) -- so I have to deal with not refreshing this component when the state updates (visually it's perfectly fine since the browser updates it anyway).
