### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by jgpacker** [isaacHagoel/svelte-dnd-action#143]
Now that Svelte supports it, would you consider migrating this project to TypeScript ?

I am proficient in TypeScript and can help!

**Comment by isaacHagoel** [comment]
Hi,
Yes. I am totally open to that. First and foremost, we don't want typescript users to get red in their editor when they use the library.
What do you have in mind?

**Comment by jgpacker** [comment]
I gave it a try today in my fork, and it's easier to migrate than I expected, thanks to the JSDoc annotations.
Work in progress: https://github.com/isaacHagoel/svelte-dnd-action/compare/master...jgpacker:master

Here is what I'm thinking:
* Replace JSDoc annotations by TypeScript types;
* At first, avoid changing code as much as possible, focusing on the types. And avoid exposing types to users yet;
* Make sure Tests and Build are working as before;
* Then, try to make types stricter without breaking the contract specified in the documentation. And only then these types can be made "public", and announced to users.

What do you think?

**Comment by jgpacker** [comment]
Initial migration  (that avoids modifying code behavior) is done, and Cypress tests are running fine.
Build configuration still needs to be reviewed.

**Comment by isaacHagoel** [comment]
@jgpacker Wow. That was fast. Nice work! 👏 👏 
I gave it a brief look and everything I saw made sense to me.
Please let me know if you need help with the build configuration. I am working an a React library (custom hook and a small flip animation util) that will allow using this library within the React ecosystem. It actually works really well and is tiny compared to the alternatives. It is almost ready as far as functionality goes, but I haven't made it public yet. It is important that the library builds correctly so it can interop. If svelte-dnd-action becomes typescript (thanks to your help), I guess the hook will become typescript as well.

When I have some time (will try to make it happen tomorrow but let me know if it's better to wait for a pull request), I will review your changes in detail, clone it and test locally with all of the examples I have to see that nothing is broken.

We'll also need to test it with a typescript svelte app to see that it complains when it should and doesn't complain when it shouldn't. I haven't tried the typescript integration yet and not sure how it works within the svelte templates in the context of custom actions.

**Comment by jgpacker** [comment]
I created a draft PR so you can already start commenting. I was not able to fix the build yet and need to sleep. I will try again tomorrow.

**Comment by isaacHagoel** [comment]
hi @jgpacker,
I looked at it in more details and here are my thoughts:
1. I appreciate the effort and think u totally deserve a T-shirt and a spot in the contributors list for this repo
2. As I said above, first and foremost, I don't want typescript users to get red in their editor when they use the library. Without an exported type definitions file, this goal is not achieved. 
3. I don't want to have typescript in this repo just in order to say it has typescript, while allowing implicit any and such. I cloned your branch and changed the flag so implicit any is not allowed and got a bazillion errors. It looks like fixing them would require jumping through all kind of hoops just in order to make Typescript happy (without improving the code quality).
4. It looks like there is an [official way](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) to generate type definition files from JSDoc (maybe it will need to be tweaked a bit) as part of the build process and get the best of both worlds without the extra overhead. This will not break the build either and won't slow down development in the future.  

I know this is not what you were hoping to hear and I apologise. I couldn't know in advance.
Are you open to looking into option 4 (if so pls create a branch from most recent master)?
If not, l can look into it and would still like to help you get that T-shirt somehow

**Comment by jgpacker** [comment]
I know about dts-gen, but we need to review it manually anyway.
The easiest approach would be to just declare the types of the functions being exposed by the module.
But I am also migrating the codebase (1) to help get the static analysis benefits, (2) to help ensure the exposed types are correct and up-to-date, and (3) to personally get the experience of this kind of migration.

I don't think we need to enable all strict checking options, which is what would require "jumping through all kind of hoops" in order to make the code compliant.
But I understand that having implicit `any`s all over the main code is not helpful, so here is what I suggest: Let me enable the `noImplicitAny` strict check and disable `strictNullChecks`. This check `strictNullChecks` is the one that would require the most code behavior changes, and it would be especially annoying to use in pointerAction and keyboardAction, because they keep state in "possibly undefined" variables and would need to check every `Map.get` and such.

I'm adding `// @ts-expect-error` for lines that require change in code behavior to become compliant to some strict check, and I will create another PR to fix most of these (to avoid tricky bits, significantly reducing PR review complexity). And rest assured that I have incentive from Hacktoberfest to create more PRs, so I will definitely come back to do it.

The t-shirt is an incentive to do it now instead of waiting for it to happen, but I also want to use this project in [my webextension configuration page](https://github.com/jgpacker/osm-smart-menu/blob/34cdb488f80cc739e60e0456ebc3ec0b6e82f572/src/options/utils.ts#L5).

We can already expose types in the current PR. I was not going for it because yet because I wanted to break the migration into incremental deliverables, but let me try.

**Comment by jgpacker** [comment]
@isaacHagoel Now `noImplicitAny` is enabled,  which should greatly improve the developer experience.

I'm struggling with making Babel compile the TypeScript files with Rollup. Could you help me with that?
I tried based on https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html and https://babeljs.io/docs/en/babel-preset-typescript

After that, we just need to use TypeScript to check the types and generate the type declaration files

**Comment by jgpacker** [comment]
Also, I want to review with you the main types exported in `action.ts`.
Does `Item` always have `name` ? Or `id`? Does `transformDraggedElement` still receives any parameter? Can `type` be any string?

**Comment by isaacHagoel** [comment]
thanks.
to your questions: 
`type` can be any string
each item must has an id, the name of the id property is determined by the overridable (globally) `ITEM_ID_KEY`
the signature of transformDraggedElement is:
function(element, data, index) {}
element: The dragged element.
data: The data of the item from the items array.
index: The index the dragged element will become in the new dnd-zone.

i guess element is mandatory (otherwise, what will it transform)  and the other two params are optional 
I didn't have a chance to look at your code and the build issues today but I will make some time tomorrow

**Comment by isaacHagoel** [comment]
@jgpacker I wanted to look into the build issues so pulled your latest master but `tsc` still has a lot of errors (20).

I've tried the jsdoc conversion thing to see how far it could get us and documented my findings [in this draft PR](https://github.com/isaacHagoel/svelte-dnd-action/pull/149). You might have insights into the missing bits.

I really want to get to a point in which we can actually try one of these solutions within a typescript-svelte app and see what it does and how vscode and svelte deal with it in context (`use:dndzone=... on:consider=...` ).

**Comment by jgpacker** [comment]
There should be no errors on `tsc`. You are probably using an older version of TypeScript that does not recognize the annotation `// @ts-expect-error`.
Try using the one inside node_modules.

I didn't get to this point yet, but I believe we will need to configure the location from the type declaration files in `package.json`.
I wasn't aware about possible issues with `on:consider` type on svelte components. But first I will focus on making the build work.

**Comment by jgpacker** [comment]
@isaacHagoel I added a command `tscheck` in `package.json` to make it easier to use the `tsc` inside `node_modules`.

About the build, I made progress by compiling typescript before rollup. Having two output files in rollup is what complicated things.
Next step (some other day) should be testing type recognition in Svelte.

**Comment by isaacHagoel** [comment]
@jgpacker thanks for the update. I've make progress on making svelte cooperate. it applies no matter how the type definition files are created I believe. I documented my findings [in this comment](https://github.com/isaacHagoel/svelte-dnd-action/pull/149#issuecomment-708911482). There is one thing I couldn't get quite right (not having to explicitly type the event handler) and the whole `global.d.ts` solution is quite ugly (though inevitable at this point in time).

You were right about me having an older typescript version installed locally. Upgrading it made the tsc errors go away. I am still uneasy about having to use  @ts-expect-error in 20 places (and allowing nulls everywhere). I am not saying we should change it but it does go against the value proposition of typescript.  

I am also debating with myself on whether it is best to just create the type definitions manually and be done with it. I have never made a breaking change to the API so far and not planning to in the future, so I will only have to update the file when exposing new options.
The ease of it is tempting: just add index.d.ts (which we basically already have), have the build copy it to dist folder, add the 'types' entry to package.json, add the information in the comment I linked above to the README and all done.

I am concerned that typescript will slow me down considerably without providing any value beyond what I already get from JSDoc. Did you find any bugs in the library thanks to doing this integration? I don't think the library users care about which language it is written in. They just want it to be robust, light, fast, easy and and work with whatever they are using.

Now, that you've been working on this for awhile, what is your take on this? If you were me and had to keep maintaining and enhancing this library. Do you feel like typescript is a good fit in this case?

**Comment by jgpacker** [comment]
I use TypeScript in my open source project and in a major project where I work (using Next.js and React). I have also given a talk twice on how to take more advantage of TypeScript's type system.

Personally I see TypeScript as "JavaScript with explicit types" (see [TypeScript Design Principles](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals)), so I would say TypeScript would not fit where you cannot use compilation or something like a really simple and small project, where it's not even worth it to setup compilation for some reason. Other than that, I would recommend it, including in this case.

I can't say there will be no learning curve, but I would expect it to be low, and that the static analysis would make you more efficient in changing existing software such as this one.

How about we have a video call about this issue to go over the other details? Send an email to joao.g.packer+TS@gmail.com

**Comment by isaacHagoel** [comment]
Hi,
I also used "real" typed languages extensively (like Java, C++ and C) and I have used typescript on some projects too. 
It is not ignorance that makes me worried in this context, but experience 🧓.
 
I went over the [list of bugs](https://github.com/isaacHagoel/svelte-dnd-action/issues?q=is%3Aissue+label%3Abug+is%3Aclosed), I have fixed in this library since its inception, looking for bugs that could have been prevented by a typechecker. I've found zero such bugs.

I am totally onboard for enabling typescript users to consume this library. That's a no-brainer.
I also intend to add typescript to the React adapter for this library (a hook and flip animation util), which is much smaller and less dynamic that the library itself.
Let me think about it some more. Thanks for offering the video chat. I appreciate it.

**Comment by jgpacker** [comment]
Ok, so I will list here the list of possible problems that TypeScript found:
* JsDoc definition of Options did not contain "autoAriaDisabled", and contained "dragTargetStyle" instead of "dropTargetStyle";
*  `draggedEl.name = 'dnd-action-dragged-el'` instead of `draggedEl.setAttribute('name', 'dnd-action-dragged-el');` (`name` isn't a standard attribute in `HtmlElement`, but I haven't tested the actual differences between these implementations in real browsers);
* functions `styleActiveDropZones`, `styleInactiveDropZones`  have a parameter `getStyles` with default value `() => {}`, which is incompatible with the way it's used
* function `unobserve` needs no parameters, but it's receiving 2 parameters inside `unWatchDraggedElement`;
* function `handleDragStart` needs no parameters, but it's receiving 1 inside `handleMouseMoveMaybeDragStart`

**Comment by isaacHagoel** [comment]
Thanks for the list!
I think it is fair to say that even though these problems shouldn't exist in a codebase and it is bad that they slipped in, none of them has any real effect. 
I will use your MR in order to create a type definition file and update the README to explain how to make svelte not complain about the handlers when using typescript.
I might revisit this decision in the future but I can't go forward with a full on migration to typescript at this point in time.
I now have a much clearer understanding of what this would entail.
I super appreciate your contribution and patience here and I apologise for not being wise enough to know this in advance.
