### ISSUE TITLE
Dnd crashes when in:scale and out:scale is added inside the card

### ISSUE THREAD

**Issue by thousandsofraccoons** [isaacHagoel/svelte-dnd-action#157]
Please take a look at REPL: 
https://svelte.dev/repl/e9886667f71e408eb495999bf5cd540e?version=3.22.2

lines 35 , 36 in tooltip.svelte

**Comment by thousandsofraccoons** [comment]
Hm, it crashes even without Popper. I've cleaned up the repl to exclude code which doesn't affect the bug.

**Comment by thousandsofraccoons** [comment]
Also, last version 6.1.0 contains `aria.js` which throws following error in Sapper:
```
let alertsDiv = document.createElement('div');
                ^
ReferenceError: document is not defined
```

**Comment by isaacHagoel** [comment]
Svelte's built-in out transitions don't work well with the library. That's because they try to delay the removal of the transitioned element from the dom. 
There are some examples for workarounds in the examples section in the readme. Let me know if you need help with doing the same for scale.
Regarding breaking Sapper, sorry for that, there is another issue (opened that same day as this one 😄 ) that covers that: #159. Will probably be fixed within the next day or two.

**Comment by isaacHagoel** [comment]
closing this for now. pls let me know if i can assist further.
