### ISSUE TITLE
Make console.debug() output configurable

### ISSUE THREAD

**Issue by pReya** [isaacHagoel/svelte-dnd-action#165]
Internally you're using `console.debug()` to output info to the console. However this seems to be an alias for `console.log()` in most browsers. It would be great to enable/disable the debug output via a boolean config variable.

Is there any other mechanism to disable debug output? Would you be accepting PRs to implement this?

**Comment by isaacHagoel** [comment]
Hi @pReya 
I was under the impression that console.debug works the same on all browsers (and [has full support](https://developer.mozilla.org/en-US/docs/Web/API/Console/debug)). However, I tested it and even though Chrome and Firefox behave as I expect, Safari seems to be showing all log levels by default. 

With that said, I am totally open to making this library less spammy on the console. There was even [an issue for it](https://github.com/isaacHagoel/svelte-dnd-action/issues/54) that I ended up not doing.
The things to get right are:
1. What is a proper way to enable/disable debug mode? I wouldn't want it to be an option that is passed into the action because that contaminates the API and makes it problematic to implement (because some debug logs are global and because we would need to account for enabling/disabling without restarting the app). Another option is to make it an internal variable that has to be set in the code. That means no debugging in the REPL.

2. What is a proper implementation? ideally it won't involve checking an `if` condition every time. One possible solution is to have a printDebug variable that will be set to an empty function (`()=>{}`) when not in debug mode and to a function that prints to the console when we are in debug mode. We could then call the function from the code printDebug('hello') as much as we want without triggering `if` checks.

Thoughts?

**Comment by pReya** [comment]
Thanks for your answer @isaacHagoel!

Aside from Safari not behaving as expected: Setting a log level in the browser only changes, which messages the user gets to see. I would like to have control over which messages are actually created. I don't want to log anything to console in production – no matter the browser setting.

1. I see your point. Having this as an option for the action would indeed "dillute" the API a little. However I think this is still a better option than making it an internal variable, which would need to be set in the `node_modules` folder (which is a pain, because it's typically not checked into git and therefore not persisted to my dev environment – it would be gone on a new machine). Another possibility is using a second export, e.g. (`import {dndzone, dndzoneDebug} from ...`) but it's also not very nice.

2. Yeah, using a noop function seems like a good idea to handle this.

**Comment by isaacHagoel** [comment]
Fair point about logs in production.
About #1, I guess the best and simplest to implement option would be an export that overrides that global printDebug function . Similarly to the existing `overrideItemIdKeyNameBeforeInitialisingDndZones`.
Maybe something like `setDebugMode(boolean)`.
I believe 99.9% of users will not need to use it or care about its existence. 
This would allow debugging in the REPL as well and should be straightforward to implement.
Makes sense?

**Comment by pReya** [comment]
So, if I understand you correctly, you'd prefer it to look like this, right?

```
<script>
import {dndzone, setDebugMode} from 'svelte-dnd-action';

setDebugMode(false);
</script>
<section use:dndzone=...>
```

**Comment by isaacHagoel** [comment]
Should be `false` by default but otherwise i think so, yes

**Comment by pReya** [comment]
Yeah, I agree it should be false by default. I just thought that's the way you like it, b/c it's more like your current default setting (which logs everything – only shows depending on browser setting).

I'll try to whip up a PR during the next days.

**Comment by isaacHagoel** [comment]
Cool. Thanks

**Comment by isaacHagoel** [comment]
@pReya 
I suddenly recalled an article I read one.
The printDebug function should probably take a function that returns a string (or that returns an array of stuff to print, the way console.debug expects it) rather than taking a string as I proposed above.
Something like:
```javascript
function printDebug(makeDebugString) {
   console.debug(makeDebugString());
}

``` 
This is better than taking a string because this way calling the no-op function becomes much cheaper.
Many of the debug strings involve JSON.stringifying the items array or other objects (via the `toString` method in utils). 
Calling
```javascript
printDebug(() => `look at this fancy object ${JSON.stringify(bigObject, null, 2)}`);
```
will not stringify anything when debug mode is off (noop function) which means better performance and not doing any throwaway work. 
Makes sense?

**Comment by isaacHagoel** [comment]
hi @pReya 
did you have time to work on this one?
Thanks
