### ISSUE TITLE
[QUESTION] Is it possible to do a nested/tree-type draggable list?

### ISSUE THREAD

**Issue by danawoodman** [isaacHagoel/svelte-dnd-action#168]
Awesome library!

I was wondering if there is an example or documentation on how to do nested lists, for example a list like:

1. Item
2. Item
    1. Item
        1. Item
    2. Item
3. Item

Could you drag and item, say `2.i.a` to the root level and/or drag as a sub item of something, say `3`?

Thanks for any direction you can give!

**Comment by isaacHagoel** [comment]
Hi,
In the examples section, there is one called [crazy nesting](https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.29.4). Does it help?
Thx

**Comment by isaacHagoel** [comment]
@danawoodman does the answer above resolve this or should i leave the issue open?

**Comment by danawoodman** [comment]
@isaacHagoel yes! That's great! Maybe it could be in the readme or did I miss it? Thanks 🍻

**Comment by isaacHagoel** [comment]
It's in the readme. It's title is "crazy nesting" :)

**Comment by kimaldis** [comment]
I'm working on something similar. Crazy nesting almost does it for me, I'd like to be able to drag, say, node 3 onto node 2, making it a sub node of 2. Or item 9 onto item 5, making 9 a child of 5 in addition to inserting it after 5. SOme way of distinguishing between drag onto and drag after

Generalising, I'd like to be able to drag any leaf or branch onto any other leaf or branch, rearranging the tree in any way possible.

I'm halfway into a solution using vanilla draggable. It turns out to be a little tricksy.
kyp.

**Comment by dror-weiss** [comment]
@kimaldis , were you able to find a way?

**Comment by kimaldis** [comment]
Sorry, no.

**Comment by isaacHagoel** [comment]
if someone provides more structured requirements/explanation of the expected behaviour i might be able to help
