### ISSUE TITLE
Handle dnd elements more dynamic

### ISSUE THREAD

**Issue by Florian-Schoenherr** [isaacHagoel/svelte-dnd-action#187]
[REPL of what I'm trying to accomplish](https://svelte.dev/repl/dc42a5780ab54666a103fbdc95cb2229?version=3.29.7)

This errors twice:
![errors](https://user-images.githubusercontent.com/65456722/99960972-ede86080-2d8d-11eb-840b-5b9e1528cc3a.png)

I hope this will be possible, this way you could use a dnd-action "annotated" element as a sort of dynamic container.

**Comment by isaacHagoel** [comment]
Hi @Florian-Schoenherr ,
I would be happy to understand the usecase better. 
It happens because the number of children is different (larger) that the number of items. Not sure why the slot causes that.
```javascript
for (let idx = 0; idx < node.children.length; idx++) {
            const draggableEl = node.children[idx];
            styleDraggable(draggableEl, dragDisabled);
            if (config.items[idx][SHADOW_ITEM_MARKER_PROPERTY_NAME]) {
```
`config.items[idx]` in the last line is undefined.
The fix might be as simpler as looping over the items instead of over the children. I am super busy atm. Can try to get to it or be my guest to try.

**Comment by Florian-Schoenherr** [comment]
usecase: I will use a Component consisting of <svelte:component> inside the slot and also nest multiple dnd zones, don't know if that helps.
If you can try, that would be nice, otherwise I'll look at it on a weekend.

**Comment by Florian-Schoenherr** [comment]
Testing around a bit, I did `console.log(node, node.children);` and tried some combinations of looping/using items/children.
I only found out that it may have to do with slots, because `node.children` = `[]` and if I understand correctly, node.children are just the html children?

**Comment by isaacHagoel** [comment]
@Florian-Schoenherr yes, u understand correctly.
i also played a tiny bit (tried to change the loop) and it didn't help. i didn't dive super deep into the svelte source code to discover how it manages its slots.

**Comment by Florian-Schoenherr** [comment]
@isaacHagoel btw, why did you decide to use an action instead of a component for dnd?
I know that actions are like "js-only" and you can decide for yourself which html-element you put it on, but other than that I know nothing. There is another lib with the component approach, but much less functionality.
I'm also asking because (don't quote me on this) I would like to contribute.

**Comment by isaacHagoel** [comment]
@Florian-Schoenherr  I went for an action for several reasons:
1. **How clean, elegant and simple the resulting API was** (while still giving me, the library author almost unlimited power): No need for slot and strange slot props (probably my least favourite feature in all of svelte) , no need for multiple wrapper types (ex: one for the container and another for an element) or anything like that. It is true that sometimes there can be conflicts with Svelte when both try to control the DOM (ex: fade out transition). Those are usually easy to work around and I am not sure whether a component based approach could have avoided these (assuming it would have to bind on DOM elements in order to match the level of sophistication that this library has). 
2. **Portability** - There is nothing in the code that is svelte specific (in other words, svelte is not a peer dependency). The library solves the drag and drop problem in a general way. In fact, it is quite easy to port it to other ecosystems. For example, see [react-dnd-action](https://github.com/isaacHagoel/react-dnd-action), which I have implemented as an experiment but didn't really try to push thus far. It works great though.
3. Given point 2, it is probably not hard to wrap the code in a component based implementation for Svelte if there is a desire to do so. I don't think it would be as nice of an API, but maybe I just haven't thought of the right abstraction.

I won't quote you but contributions are welcome.

**Comment by Florian-Schoenherr** [comment]
Portability does make much sense. I wonder how performance compares to the component approach (https://github.com/kyythane/svelte-reactive-dnd), though.
Also, this issue should make it possible to wrap it in a component, the REPL essentially does that.

**Comment by isaacHagoel** [comment]
@Florian-Schoenherr i dont see any way in which performance can suffer because of choosing to implement as an action.
The Library you linked to uses slot props which i personally think is an anti pattern (breaks encapsulation)

**Comment by isaacHagoel** [comment]
About the Repl doing this kind of wrapping. I don't think it is the case.
The wrapper component should not use double binding on the items (inner and
outer). It should probably be more similar to how the library in the link
does it.

**Comment by Florian-Schoenherr** [comment]
You're right, I should change that. I guess now we only need to check for empty `node.children`? Although it should not loop then? hmm

**Comment by isaacHagoel** [comment]
I don't think any changes would be necessary if you wrap it similarly to
how the library does.
Otherwise, i don't think that simply checking for empty children will
solve the problem (you can try) because a discrepancy between the children
and the items breaks a key assumption that the library makes.

**Comment by Florian-Schoenherr** [comment]
New [REPL](https://svelte.dev/repl/85b9d8afcedd43a8a594ae4c4cf979f5?version=3.29.7).
what did I miss?

Also, I thought this is using `items` with ids exactly because there could be discrepancies (although right now the problem seems to be something else, let's just focus on that)

**Comment by isaacHagoel** [comment]
Hi,
Are you trying to create a generic list component that can accept an arbitrary list item?
If so, how about something like this (MyItem is the arbitrary list item)?
https://svelte.dev/repl/028674733f67409c94bd52995d5906f1?version=3.31.0

**Comment by Florian-Schoenherr** [comment]
This could work for my usecase, I will test that.

**Comment by isaacHagoel** [comment]
I made small improvements to it right now. please refresh.
maybe i will add it as an official example if it works for you.
in my opinion this is much nicer that the slot based approach (as you probably understand I find slot props to be a huge unintuitive mess 😸 )

**Comment by Florian-Schoenherr** [comment]
Works quite well! We could close this, maybe after the official example.
I don't have any usecase in mind where someone would need slots for this anymore.

**Comment by isaacHagoel** [comment]
I am glad it works. added to the README
