### ISSUE TITLE
Select Elements Preventing Dropping

### ISSUE THREAD

**Issue by ezfe** [isaacHagoel/svelte-dnd-action#204]
I have an html `<select>` element that's interfering with my drag-and-drop. What's the best way to resolve this?

Here is a REPL sample project (courtesy of @isaacHagoel) that demonstrates this issue. I'm able to reproduce it in Safari 14.0.3 and Firefox 85.0b4

https://svelte.dev/repl/f29ffe920bef4397be5156be9a831e9d?version=3.31.0

**Comment by isaacHagoel** [comment]
Hi, it doesn't seem to reproduce for me. what am i doing wrong?
I am on Chrome on a Mac. Also, it would be the easiest if u could reproduce in the REPL.
https://user-images.githubusercontent.com/20507787/103329760-61c70880-4ab2-11eb-899b-b4629f6230a2.mov

**Comment by ezfe** [comment]
@isaacHagoel I'm using Safari - and I just tried it in Firefox, where it also isn't being reproduced. I think it's just a Safari issue. I'll deal with this then, thanks!

**Comment by isaacHagoel** [comment]
I am able to reproduce it on Safari using the [REPL](https://svelte.dev/repl/f29ffe920bef4397be5156be9a831e9d?version=3). will look into it

**Comment by ezfe** [comment]
I'm able to reproduce this in Firefox with your REPL example, but not my original example.

**Comment by isaacHagoel** [comment]
It happens because on Safari (i didn't try ffx) clicking the select triggers a mousedown event but does not trigger a mouseup event (at the end of the click). The library thinks the the mouse is down and sees that the mouse moves which initiates a drag.

One solution is for the library to ignore select elements altogether (meaning the user won't be able to initiate a drag by clicking on it) but there might be a better approach. 
How urgent is this for you?

**Comment by isaacHagoel** [comment]
fixed in version 0.7.1.
keyboard drag already ignores nested input element. makes sense for pointer (mouse/ touch) drag to do the same

**Comment by ezfe** [comment]
Thanks! I did need a drag-and-drop solution in Svelte and this seemed like the best one. I'll let you know if I run into any issues when I update it.

**Comment by ezfe** [comment]
I can confirm this fixed my website as well - thanks for the quick fix

**Comment by isaacHagoel** [comment]
cool. thx for letting me know.
