### ISSUE TITLE
Unexpected movement on large items

### ISSUE THREAD

**Issue by yjp20** [isaacHagoel/svelte-dnd-action#211]
Demo:
https://svelte.dev/repl/dc83f9ba1a0a4c8794cffd558d7e213d?version=3.22.2

I've made the item 45 very large in comparison to the other elements. When you start dragging the large item, the bottom items unexpectedly rushes in, displacing the shadow element.

From what I can tell, this library uses the center of the current dragging element to determine the position. If the dragging element is more than twice the size of the element before it, then at the moment you start dragging the center will actually be below the next element. To put it more concretely, if you start dragging element N then N+1 will takes it's spot since the moment you start dragging, element N's center point is below N+1.

In doing more research, it appeared to me that react-beautiful-dnd compares the top / bottom point of the current dragging element to the center of the other elements, rather than the other way around. This results in a behavior that's probably more expected to the user.

**Comment by isaacHagoel** [comment]
This library indeed uses the centre of the dragged element and checks whether it is inside an item to decided whether it needs to take its place (I actually took this idea from react-beautiful-dnd :)). after the item moves for the first time, it caches the location of the shadow element so that it gets "smarter" as you keep dragging the item around (meaning the item below might "rush" once per drag but after that it doesn't get fooled by the dimensions differences).

it makes no assumptions about the layout of the list (horizontal, vertical or any other shape like multi rows would work). 

I am open to suggestions for improvement, please explain the algorithm you suggest in more details.

I don't think the REPL you used as an example reflects a realistic usecase though (at least not one that I have seen so far).

**Comment by yjp20** [comment]
I do know that it's what react-beautiful-dnd said in their Medium post, but it seems like that's not *actually* the case. It's done the other way around for some reason.

I've extensively tested this, but it truly seems like instead of checking whether or not the center of the dragging element is in another element (as they say in their drag post), it checks whether or not any center is within the current dragging element. This may be as simple as changing the order of the arguments in the following line.

https://github.com/isaacHagoel/svelte-dnd-action/blob/a342a6ac3af3d4906108064a00349cfce3e4bd47/src/helpers/listUtil.js#L58

However, I was reluctant to test this since I couldn't quite spend the time to understand the caching algorithm.

I maybe explaining this in a pretty awful manner, but I hope what I'm saying makes enough sense.

**Comment by isaacHagoel** [comment]
Interesting. I will give it a try. Thanks.

**Comment by isaacHagoel** [comment]
@yjp20 I had a few min so i gave it a quick try. it is not as simple as changing that one line (i also disabled the cache optimisation to make sure it doesn't get in the way). 
As I was playing with it one important question came to my mind:
The centre of more than one of the underlying elements can be inside the dragged element at any given time, especially when the dragged element is big and can theoretically cover all of the other items combined. To make it worse, it can simultaneously be over centres of items from multiple lists.
What should the algorithm do in such a cases? 

BTW, another approach could involve improving how the cache is created, because once it's there the issue disappears. I will give it some more thought.

**Comment by isaacHagoel** [comment]
@yjp20 good news: I found an approach that seems promising based on some quick experiments. I will let u know when there it is ready (i will need to find roughly 2 hours to implement it properly and test).

**Comment by isaacHagoel** [comment]
@yjp20 if you have a chance give the branch "211-never-remove-shadow-element" a try. The MR is still WIP (needs some more testing).

**Comment by yjp20** [comment]
Sounds great! Thanks for all your work on this.
