### ISSUE TITLE
Cannot destructure property 'items' of 'dzToConfig.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by printfhere** [isaacHagoel/svelte-dnd-action#241]
Hey,

I have a small issue when trying to create a DnD TreeView with svelte-dnd-action.

Here is the REPL: https://svelte.dev/repl/a6b386d252dd42ebbbc416134c65b581?version=3.32.1

It seems to work but in the console I have an error when trying to move a folder: 

Uncaught TypeError: Cannot destructure property 'items' of 'dzToConfig.get(...)' as it is undefined.

Did I do something wrong in my code?

Thank you for your amazing work!

**Comment by isaacHagoel** [comment]
hi,
the problem is the placeholder item that gets added for basically one frame on drag start and has an id that is not in your data structure (because the library allocates a temp id and then replaces it with the real id right after).
this fixes it but you probably want to make it nicer by checking against the original ids  :)
You can see how it is done in the "Crazy nesting" example in the README.
Maybe I should export the temp ID to make this easier.
```html
 {#each items as item (item.id)}
      <div class="item">
				{#if item.id < 100}
           <svelte:self tree={item} />
				{/if}
      </div>
    {/each}
```

**Comment by printfhere** [comment]
Hey! It took me a while to understand what was going on but I now have a better understanding of the situation. I didn't want to use the same structure as you did for the tree but I used the same idea and passed a list of all the ids in my tree to be checked.

Here is the result, may this help others: https://svelte.dev/repl/287a74d81da24f5fadf3364dea125b1c?version=3.32.1

I close the issue, thanks again for your help and your work on this cool tool!

**Comment by isaacHagoel** [comment]
thanks. do you think the library should export the temp id it uses so it is easier to filter the temp item out?

**Comment by printfhere** [comment]
Yes I think that's a good idea, I wanted to filter the shadow placeholder on its name but thought that if it came to change it would not work. However if it was exported, one could easily filter it and code would be cleaner.
