### ISSUE TITLE
expose the ID of the dragged element so it can be styled or manipulated imperatively 

### ISSUE THREAD

**Issue by tomasmoose** [isaacHagoel/svelte-dnd-action#267]
Example [repl](https://svelte.dev/repl/9a187d0399014514b909171829852075?version=3.24.1) based on the Dragula example. I assume `transformDraggedElement` would have to be called [here](https://github.com/isaacHagoel/svelte-dnd-action/blob/574e4fc7484dbf7c380b556a5dde285c81a2fd1b/src/keyboardAction.js#L244) or maybe I'm missing something? thanks for a great library!

**Comment by isaacHagoel** [comment]
in your REPL you would notice that when an element from the other lists enters the dragula list it does gets transform but when it is an element from the dragula list enters it doesn't.
This is intentional (though it might not be what you need for your usecase).
Currently `transformDraggedElement` is called when the shadow item is detected within a list, as in when the element entered a list that is "willing to accept it" into a specific index.
The dragula list doesn't accept copies right after they were created so there is no shadow element so there is no transformation. It communicates to the user that dragging over the list has no effect.
Does it make sense?

**Comment by tomasmoose** [comment]
Hi! thanks for the explanation, this makes sense, in my use-case I'm going to have quite a large nested list that acts as a "you can only copy from me", so wanted to (crop) the dragged element when dragging and show _x more items_  instead of having a large drag area that blocks the view. But can figure this out with styles if it breaks the flow!

**Comment by isaacHagoel** [comment]
It's easy for me to include the dragged element as an additional property
in the consider/ finalize events. Will that help?

**Comment by tomasmoose** [comment]
That would work perfectly for this case, thank you!

**Comment by isaacHagoel** [comment]
@tomasmoose how does your usecase play out with keyboard drag? no transformation should take place, right? 
That means your handlers will need to only transform when the source is `SOURCES.POINTER`...
Please confirm.

**Comment by tomasmoose** [comment]
This would not play in on keyboard drag, would not make too much sense, so don't think it would be needed there, but could point in bringing it up

**Comment by isaacHagoel** [comment]
@tomasmoose I implemented it (didn't push) just to realise there is a much simpler solution.
I can export the id of the dragged element as a constant. 
The id can be used to retrieve the dragged element (getElementById) in the finalize/consider handlers or whenever (with caution). 
Am I missing something or will it address your need?

**Comment by tomasmoose** [comment]
Hi @isaacHagoel, exposing `id` would also work from my side, and yes sounds a lot simpler and cleaner solution so would go forward with that, from my side just grabbing the element with `getElementById` or similar would work perfectly!

**Comment by isaacHagoel** [comment]
@tomasmoose I've made and release this change. thanks.
