### ISSUE TITLE
Can I specify my own ID key field?

### ISSUE THREAD

**Issue by newlegendmedia** [isaacHagoel/svelte-dnd-action#308]
Is there some way I can override or modify the key field name (which is a constant defined as "id") ?

My items have a key called "key" and it causes extra problems to rename it in my system.

**Comment by isaacHagoel** [comment]
https://github.com/isaacHagoel/svelte-dnd-action#overriding-the-item-id-key-name

**Comment by newlegendmedia** [comment]
Thanks!  I should have seen that :-)

**Comment by TheophileMot** [comment]
@isaacHagoel I had a similar issue where I wanted to use a different variable name for `items`, let's say `myItems`. It didn't work when I tried `<div use:dndzone={{ items : myItems }}`, but I experimented and found that this seems to work:

```
  const myItems = [ ... ];
  $: items = myItems
```

and then `<div use:dndzone={{ items }}` as usual.

Is this a reasonable (i.e., safe) approach? I was surprised that it worked, because I didn't expect the binding to go both ways (i.e., when dnd updates `items`, I didn't think `myItems` would be updated too).

**Comment by isaacHagoel** [comment]
Items:myItems should work with no issue. repl pls

**Comment by TheophileMot** [comment]
Here is a [REPL](https://svelte.dev/repl/4a4aae41e6e04edf8e89b6dbee3c11a4?version=3.46.3) demonstrating the broken behaviour.

Also, I was wrong about my comment about two-way binding (I was right to be surprised): my callback was still referencing `items` as opposed to `myItems`.

**Comment by isaacHagoel** [comment]
In your repl all u need is to fix handleSort.
Should be
`myItems = e.detail.items`

**Comment by TheophileMot** [comment]
Oh, of course. Sorry, I guess I was too tired. Thanks for your help and for providing this great library.
