### ISSUE TITLE
Autoscroll makes dnd "unresponsive"

### ISSUE THREAD

**Issue by mataslib** [isaacHagoel/svelte-dnd-action#312]
Drag item, do autoscroll, dnd then stops to be responsive or starts behave weird.

![autoscrollbug](https://user-images.githubusercontent.com/5154014/128029113-75228d2e-353e-44d4-a92a-72c6c7a131cd.png)

Seem not to happen unitl one does autoscroll.

Repl: https://svelte.dev/repl/4a542b9bb2554507b8e333c75816c460?version=3.22.2

Gif:
![2021-08-03-16-19-20-min](https://user-images.githubusercontent.com/5154014/128032645-f1894066-7141-44d7-b1a3-d31bd0443aed.gif)

**Comment by isaacHagoel** [comment]
doesn't reproduce for me (macOS + chrome).
which os + browser are you using?

**Comment by mataslib** [comment]
Win10 + chrome. As you can see in gif, I have to try for a while till I break it (broke after 4th autoscroll).

**Comment by isaacHagoel** [comment]
sorry. i was busy with other stuff. will try to make time and look into this and the other issues you created in the coming days. it goes without saying that I am open for pull requests :)

**Comment by IcyFoxe** [comment]
Same problem here, it bugs out quite easily on autoscroll (I implemented my own version of autoscroll, but the problem is the same as described above). I'm pretty sure scrolling the page messes up the calculations this library makes for elements in the list. This happens after you scroll back and forth while holding an item. After that some you won't be able to place an item between some items.

**Comment by isaacHagoel** [comment]
Thanks for reminding me to look.
I found the issue. It had to do with the shadow element cache not being reset.
I fixed it. Need to do a bit more testing and then I will merge and release.
