### ISSUE TITLE
Escape to cancel / undo

### ISSUE THREAD

**Issue by mattfysh** [isaacHagoel/svelte-dnd-action#321]
First of all, great library! I didn't know Svelte actions were a thing until now :)

I was wondering if there is a way to enable "Escape to cancel" behaviour, similar to Trello. e.g. while still dragging, press ESC and the items go back to their original state (including when dragging between multiple types)

I currently keep a copy of the original state that survives `onDndConsider`, just wondering how I can reset the internal dragging state in your action? thanks!

**Comment by isaacHagoel** [comment]
Hi,
Currently every move with the keyboard is considered a drop in order to prevent the system from being in a limbo state.
also it allows mixing mouse and keyboard dnd operations (ex: drag with the mouse while still in keyboard drag mode).
It should be possible and not difficult to make "esc" (optionally i guess) trigger a "revert" action. 
The lib could keep a copy of all lists when the user enters keyboard drag mode and have "esc" revert to that state.
I'm open to a pull request...

**Comment by mattfysh** [comment]
Hey @isaacHagoel  - I flicked through some of the source code and managed to get this working by dispatching `draggedLeftDocument` on window, which calls `handleDrop()`, and then I reset my local data back to its pre-drag state - this seems to be working well! The only downsides are a small flicker, and I had to turn off the animations that drop a card into its new position

**Comment by isaacHagoel** [comment]
yeah, that's a bit of a hack :)

**Comment by isaacHagoel** [comment]
closing for now. pls let me know if further help is needed
