### ISSUE TITLE
Is there a way to move the elements based on position of the mouse.

### ISSUE THREAD

**Issue by ivanjeremic** [isaacHagoel/svelte-dnd-action#333]
As we can see in this example the list reorders as soon as my cursor touches another element [https://svelte.dev/repl/3d544791e5c24fd4aa1eb983d749f776?version=3.24.1](https://svelte.dev/repl/3d544791e5c24fd4aa1eb983d749f776?version=3.24.1), what I want is depending on the underlying element data (the element I'm hovering, not the one I'm dragging), I want the animation/reorder not kicked off as soon as I'm over the element only at the end of the box, the reason for this is in my project some elements are apps some are folders and as we know if the element is type folder I want to be able to stay with the dragged element over the folder and drop it there, is this somehow possible and how can I get the item data of the element I'm currently over?

**Comment by isaacHagoel** [comment]
While the library uses the center of the dragged element to make decisions
about what should happen there are definitely tricks...
It would help if i understand what your GUI looks like. Can you make a
simple drawing or attach a screenshot?

**Comment by ivanjeremic** [comment]
@isaacHagoel Here is a REPL with the UI [REPL](https://svelte.dev/repl/0502bb7c2adf4f23adb6c4a356263dbb?version=3.22.2) , Please make the preview bigger so the items fil nicely. You can see when I take an app and move it over the folder it pushed the folder immediately same as it would with an app, but what I need is when its of type folder don't trigger any reorder when I go in or when I'm in the middle area of the folder Berceuse the middle is anyway the area which later needs to trigger something else if dropped there, I need to only reorder when I'm almost out of the folder to the right or left doesn't matter.

**Comment by isaacHagoel** [comment]
Shouldn't the folder also be a dndzone (so u can drop apps inside)? 
Should it be possible to drop folders in folders?

**Comment by ivanjeremic** [comment]
> Shouldn't the folder also be a dndzone (so u can drop apps inside)? Should it be possible to drop folders in folders?

Yes the folder should also be able to take folders, The project is currently in React and I'm rewriting it in Svelte, now in React I was able to just do a simple `onDragEnter` and set some states (going around creating dropzones) and simply when I drop it fires the move to the folder, What I found out in Svelte the `on:dragenter` does not even fire, Also very important for me is getting data from current element I'm, over, In React it was a piece of cake but here I searched for hours and I still have no idea.

**Comment by isaacHagoel** [comment]
A few things:
1. This has nothing to do with Svelte or React but with this lib vs. how the other lib you used. This library makes some use-cases extremely easy and other use-cases not so much, like any tool. Maybe another library can serve your use-case better and that is absolutely fine.  
2. Why would you expect dragenter to fire? I am not sure. This lib uses two events: consider and finalize. When a dragged element enters a zone you get a 'consider' with a bunch of relevant information. Same happens when wants needs to change index (which you can decide to disallow in your handlers). 
I am happy to assist but honestly it sounds like you should keep using React and the other library because it was working great and you have a solid understanding of it so why go through the trouble of switching?

**Comment by ivanjeremic** [comment]
> A few things:
> 
> 1. This has nothing to do with Svelte or React but with this lib vs. how the other lib you used. This library makes some use-cases extremely easy and other use-cases not so much, like any tool. Maybe another library can serve your use-case better and that is absolutely fine.
> 2. Why would you expect dragenter to fire? I am not sure. This lib uses two events: consider and finalize. When a dragged element enters a zone you get a 'consider' with a bunch of relevant information. Same happens when wants needs to change index (which you can decide to disallow in your handlers).
>    I am happy to assist but honestly it sounds like you should keep using React and the other library because it was working great and you have a solid understanding of it so why go through the trouble of switching?

Yeah I think you are right, it's not worth rewriting a whole app to safe on size. Thanks anyway.

**Comment by isaacHagoel** [comment]
alright.

**Comment by segovo** [comment]
Hey @isaacHagoel this functionality is also actually something I'm trying to achieve as well. I have a list style app which displays post and folders. Since it's a list, it actually works pretty well out of the box if I manipulate the drop zone to be larger than a standard post, that way the post runs into the drop zone before it would try to switch positions.

The problem is that if I move a post high in the list down into a folder lower in the list, the shadow then disappears and the folder jumps into the posts old position.

So do you have any idea on how I could force the shadow to stay inside the original drop zone until the post is officially dropped into of the folder? It's not important if a shadow is rendered inside the folder or not, I just need to keep rendering the shadow inside the posts dropzone until the post is dropped.

-- So far I've tried naively deleting some .splice lines inside pointerAction.js but no matter what the shadow always seems to leave.

**Comment by isaacHagoel** [comment]
Can you make a simplified repl and describe exactly what you want to
happen? It sounds like this could be acheived without any modifications to
the lib code

**Comment by segovo** [comment]
[Here you go](https://svelte.dev/repl/805b9bd2d5d84dd3a3d62cff94d3cb29?version=3.55.1),

If you move a post up into the folder, it works nicely, but if you move a post down into the folder, the shadows disappearance allows the folder to steal the posts spot.
![](https://media.giphy.com/media/rNFDdGCN3d7j1BzGdx/giphy.gif)

I also realized I have another problem while making this example, which is that, [if a bunch of folders are near each other](https://svelte.dev/repl/9f66b4724cf14f60a7214c8b25bec50d?version=3.55.1), a lot of things happen:

1. Any folder above a folder will immediately fall into the folder below it.
2. If you move a post or folder into a folder and then out of a folder, it will sometimes appear way below the cursor.
3. With a lot of folders or drop zones near each other, its hard to reorder anything

![](https://media.giphy.com/media/brg4bFsKh8AMzVz2Q1/giphy.gif)

**Comment by isaacHagoel** [comment]
Thanks. I will have a look tomorrow and write back

**Comment by segovo** [comment]
`#2` is actually not a problem.. changing the styling of the <div />  in the folder #each block to be positioned at the top and be 100% width and 100% height fixes it.

**Comment by isaacHagoel** [comment]
Looks like `morphDisabled: true` would help you by preventing the dragged item from shrinking when it is over the folder (normally it changes to how it would look like in the zone it is over but in the folder it doesn't look like much).
Also, on drag start (see TRIGGER) you could store the id of the item that is being dragged and in the consider handler prevent it from being removed from the list of items (keep adding it back) to prevent it from disappearing.

**Comment by segovo** [comment]
Thank you! Both suggestions worked perfectly! I was also even able to use the order of the items to change the dropzone size dynamically such that items go 3/4 the way past a folder before rearranging, rather than entirely past or past center which is great.
