### ISSUE TITLE
Does dropTargetStyle need to have a default value?

### ISSUE THREAD

**Issue by sitek94** [isaacHagoel/svelte-dnd-action#336]
Hello 👋 

When dragging an item, by default, we're getting this yellow border around drop targets, which is set by `dropTargetStyle`.

It seems to me that if someone wants to use `dropTargetStyle` they will most likely set this value to something different from the default `{outline: 'rgba(255, 255, 102, 0.7) solid 2px'}`, so for these people removing the default value won't make a difference. 

On the other hand, those who actually don't want this property set, won't have to disable it. 

What do you think? 

![Screen Shot 2021-12-08 at 20 15 01](https://user-images.githubusercontent.com/58401630/145269819-9ff3289a-036d-42ea-95a4-f6405c246c37.png)

**Comment by Fedeorlandau** [comment]
Agree, this library should ship without the default styling but still provide a way to apply it.  I'll create a PR for it in a few minutes and tag this issue.

**Comment by Fedeorlandau** [comment]
Done https://github.com/isaacHagoel/svelte-dnd-action/issues/336

**Comment by isaacHagoel** [comment]
Sorry folks. This is a breaking change. Needs a really good reason.
The default style is in order to give a visual indication that something is happening. It is done this way because it is unlikely to conflict with any pre-existing styles (ex: borders) or colors. 
Better have an ugly indication (which any app can style and make pretty) than no indication.

**Comment by sitek94** [comment]
Thanks for answer @isaacHagoel, I get your point. I'm going to close the issue then :)
