### ISSUE TITLE
Nested dnd with maximum depth

### ISSUE THREAD

**Issue by guillemc** [isaacHagoel/svelte-dnd-action#344]
Hi, first of all, great plugin!

Building upon the nested dnd examples, I've been trying to enforce a maximum tree depth. For example, let's say we have a menu where we only want to have categories and subcategories (that is, 2 levels).

(The idea is to build something similar to the [nestedSortable jQuery Plugin](http://ilikenwf.github.io/example.html))

I guess the best implementation would be that when dropping something that would exceed the max depth, it should not let you. But I really can't figure a way to do this, so as a workaround I try to "fix" the nesting of the items after the dnd actions are finalized.

Here is a repl: https://svelte.dev/repl/67f0be81647d4cbd8c67d85766236401?version=3.45.0

It seems to work fine, but it also feels like there is room for improvement (it bugs me that it fires multiple times, when different dndzones are affected).

I'm wondering if there would a better approach to build this (fix earlier rather than afterwards)?

Or, sticking to this solution, would there be a way to have only one "finalize" event for all the dndzones? I've thought about debouncing, but doesn't seem the right approach either.

Also I've been struggling to improve the fixNesting function to take a parameter with the desired max nesting level. This is totally unrelated to the plugin, and definitely should be possible, but it is really a brain teaser :)

**Comment by isaacHagoel** [comment]
Hi,
Why not simply disable drop from others when the max depth was reached. like [this](https://svelte.dev/repl/8657cb6e9c554309b5c87581414ddf0a?version=3.45.0)?

**Comment by guillemc** [comment]
Hi, maybe your example is a little different than mine (seems there's a distinction between nodes and items? why can't i drop an item inside another item?). 

Anyway I think you can't just disableDropFromOthers based only on the receiver's depth. It should also take into account the depth of the subtree you are dropping, right?

See [this example](https://svelte.dev/repl/4b95f95b163a442f9232ac081159f133?version=3.45.0), you can drop "Ties" under "Shirts", which is fine, but you can also drop the whole "Accessories" under "Shirts", which then exceeds the maximum desired depth.

**Comment by isaacHagoel** [comment]
ah, you're right. In order to account for that one could simply decide whether to disable any given zone or not on drag-start.
I fixed the example in the link to include it. It calculates the depth of the dragged item on drag-start, stores it in a store and each zone decides whether it needs to be disabled based on its own depth + the depth of the dragged item. It gets reset on finalize.
I did it in a rush but hopefully the idea comes across.

Rearding the data structure used in this example. i know it is a bit confusing. The example i based this off (because laziness) was contributed by one of the lib's users. I would have done it a bit differently but the important thing here is the concept not the specifics of the implementation. Anyways, you can't drop items into other items because of the `if` block on line 42 in `Content.svelte`.

**Comment by guillemc** [comment]
Yeah, cool solution, thanks a lot!

I've adapted the code to my example data structure [here](https://svelte.dev/repl/5e5e55f032d64364b28442cb6b63735a?version=3.45.0), in case it is useful for someone...
