### ISSUE TITLE
data array in store

### ISSUE THREAD

**Issue by pjebs** [isaacHagoel/svelte-dnd-action#358]
How can I use this library when the data array is actually stored in a writable store?

```
<script>
    import {flip} from "svelte/animate";
    import {dndzone} from "svelte-dnd-action";

    const flipDurationMs = 300;
    function handleDndConsider(e) {
        $items = e.detail.items;
    }
    function handleDndFinalize(e) {
        $items = e.detail.items;
    }
</script>

<section use:dndzone="{{$items, flipDurationMs}}" on:consider="{handleDndConsider}" on:finalize="{handleDndFinalize}">
    {#each $items as item(item.id)}
    <div animate:flip="{{duration: flipDurationMs}}">{item.name}</div>
    {/each}
</section>

```

where let's say:

```
   items = [
        {id: 1, name: "item1"},
        {id: 2, name: "item2"},
        {id: 3, name: "item3"},
        {id: 4, name: "item4"}
    ];

is the data inside the store
 ```

When I try it I get errors.

**Comment by webdagger** [comment]
<section use:dndzone="{{items:$items, flipDurationMs}}" on:consider="{handleDndConsider}" on:finalize="{handleDndFinalize}">

**Comment by pjebs** [comment]
It turned out you should not use a store.
This library and svelte conflict over the arrangement of the DOM items as they both try to dynamically manage the UI.

**Comment by webdagger** [comment]
What conflict are you referring to?
If your items are in a store, then it should just be a store.
Perhaps if you describe what you are trying to accomplish or even better a
repl.

**Comment by pjebs** [comment]
https://svelte.dev/repl/6bbb32b61504499b8baa19c8ecfcfda4?version=3.46.4

**Comment by pjebs** [comment]
you'll see that as you rearrange, the DOM gets destroyed and the UI gets stuffed up

**Comment by webdagger** [comment]
As far as I can tell, the reason the UI is garbled up is because of  `<span out:fade>{text}</span>` I assume you want to style the moving item. The library allows you to do that `transformDraggedElement`. The component being destroyed is normal from my own understanding of how Svelte works.

**Comment by webdagger** [comment]
The component being destroyed keeps triggering the `out:fade` of all the children when the item is being moved. 
Do you want to style just one child when it is moved? target it individually then, because the `out:fade` is being applied to all the children in the list and affects them when they are destroyed because the lib removes and adds them back to the dom in the new position they are dragged to.

**Comment by isaacHagoel** [comment]
The lib is not compatible with svelte's out transitions (because they make
svelte delay ripping the elements in the list out of the dom).
Having elements fade out and back in every time they change position
doesn't make much sense anyway imho.
The readme refers to it and provides a workaround and even an example
specifically for fade.

**Comment by pjebs** [comment]
The fading is actually for a non drag and drop reason.

**Comment by isaacHagoel** [comment]
Yeah look at the example in the readme. It is exactly for that. It doesn't
apply the transition while dragging only when adding/deleting elements
