### ISSUE TITLE
Elements hidden if multiple `#each` blocks iterate the same `items` array

### ISSUE THREAD

**Issue by lucadalli** [isaacHagoel/svelte-dnd-action#416]
If two lists use the same `items` array, elements from the list which is not being interacted with will become and stay hidden.
https://svelte.dev/repl/9b315abef42f434b863f1410fb44dd33?version=3.53.1

Interestingly enough, the behavior is different if the `#each` blocks are keyed with `(item)` instead of `(item.id)`
https://svelte.dev/repl/5ea285bef63f4116a27d3bf54613d658?version=3.53.1

**Comment by notme1560** [comment]
I'm having this issue too

**Comment by notme1560** [comment]
I found a workaround for my case. I had two different DnD components (with different type strings, but the same store in `items`) which were supposed to display slightly differently but rearrange the same items. 

I created a second store to track just the order of the items.
Then when the item is dropped (in `handleDndFinalize`), call `finalize()` on the second store to update the order of the real store based on the fake/temporary store
I passed `$orderStore` as `items` and it worked (the array in the `#each` also had to be referentially the same `$orderStore`).
Then inside the `each` I have to look up the rest of the data from the real store since the order store only has the IDs. 

```ts
const internalOrderStore = writable<{ id: string }>([]);

realStore.subscribe((rows) => {
	internalOrderStore.set(rows.map((r) => ({ id: r.id })));
});

const orderStore = {
	subscribe: internalOrderStore.subscribe,
	set: internalOrderStore.set,
	update: internalOrderStore.update,

	finalize() {
		realStore.update((prevList) => {
			const newList: RowData[] = [];
			get(internalOrderStore).forEach((row) => {
				const found = prevList.find((r) => r.id === row.id);
				if (found) {
					newList.push(found);
				}
			});
			return newList;
		});
	}
};
```

**Comment by isaacHagoel** [comment]
One of the rules of the lib (see README) is you can't repeat the ids in zones of the same type

**Comment by lucadalli** [comment]
> One of the rules of the lib (see README) is you can't repeat the ids in zones of the same type

@isaacHagoel Have a closer look at the repls provided. The zones are **not** of the same type.

**Comment by isaacHagoel** [comment]
@lucadalli ah lol. that's an interesting loophole I never considered - the same thing having two different types.
you can see that the lib can't comprehend that and it even lets you move items between the "two" lists. 
what's the usecase for this?

**Comment by notme1560** [comment]
In my case, I have a large table with draggable columns, but I also have a sidebar with a simpler representation of the columns to edit and reorder them easier. Both representations should always have the same order, but you shouldn't be able to drag from one to the other (and you aren't really able to, it breaks and items become invisible etc).

**Comment by isaacHagoel** [comment]
should the changes be reflected in real time? if yes, when the item is grabbed and moved around (before being dropped) how should the other list reflect it?

**Comment by lucadalli** [comment]
My use case is similar to @notme1560's and no, my the desired behavior would be for the other list to update only after the user has stopped interacting. Bonus points if it can apply a flip animation and take into account `flipDurationMs`.

**Comment by isaacHagoel** [comment]
I don't see how the library can do it. each list is treated as its own thing, not as a part of potentially N mirror lists.
It should however be possible to wrap the lib with something (maybe another action) that abstracts the extra logic that's required (effectively not using the same list of items but two instances that get synced at the app level rather than lib level) away.

**Comment by AnthonyRogge** [comment]
Hello, I think what you need is to wrap it into a component, keep the items outside and update them once dropped.

See this [REPL](https://svelte.dev/repl/1b3a0425fc9f4bdc84b9eae23efebfb6?version=3.55.1)
