### ISSUE TITLE
Usage within dialog element

### ISSUE THREAD

**Issue by canastro** [isaacHagoel/svelte-dnd-action#455]
The new [Dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) moves things to a top-layer, I'm having troubles rendering the dragged-element when using svelte-dnd-action within a dialog.

Is this a known issue? Is there a workaround? Am I missing something?

**Comment by isaacHagoel** [comment]
Not a known issue. Can you please make a REPL that demonstrates the issue?

**Comment by canastro** [comment]
@isaacHagoel here it is: https://svelte.dev/repl/a7c16138992a4c1db6b0e578952145bf?version=4.0.0

**Comment by isaacHagoel** [comment]
Thanks. I looked into it. 
It turns out that the dialog element is added to a special layer called "the top layer" that renders above anything else (including the dragged element which is a child of the document and cannot be a child of the list because svelte controls the rendering of the list).
More info [here](https://blog.bitsrc.io/top-layer-vs-z-index-for-frontend-dialogs-fcb12217a834) and [here](https://stackoverflow.com/questions/41815069/is-it-possible-to-position-a-div-on-top-of-a-dialog-tag-that-is-not-its-parent).
Not sure what I can do about it. Luckily it is easy enough to implement a dialog element that won't have this issue when there is a need to include a dnd zone inside. Marking this as a bug with a known workaround.

**Comment by canastro** [comment]
Unfortunately, in my opinion, thats not a good workaround. The introduction of the Dialog element serves a purpose and is an advancement in webdev/accessibilit. Having some dialogs using <dialog> and others a custom implementation just to support dnd doesnt sound like a future-proof approach.

Ideally we would be able to query if we're within a top-layer and append all DND elements to the root of that layer instead of appending to the body of the document.  Right now only the Dialog uses top-layer, but soon the PopoverAPI will also use it and this issue will come up more frequently (I think).

I can't find any good way to query the root of a top-layer, so for now, maybe we could, optionally, pass a reference to the element that we want to use as root?

```svelte
<section 
  use:dndzone={{ root: dialogElement, items, flipDurationMs }} 
  on:consider={...} 
  on:finalize={...}
>
...
</section>
```

**Comment by isaacHagoel** [comment]
I am open to a pull request. One thing to think about is whether there is a
need to check that the provided root element is "legal" (e.g imagine you
get one of the items in the list or whatever)

**Comment by isaacHagoel** [comment]
fixed by the merged PR
