### ISSUE TITLE
Chaos testing error

### ISSUE THREAD

**Issue by multipliedtwice** [isaacHagoel/svelte-dnd-action#490]
Hello, tried to run [gremlins ](https://github.com/marmelab/gremlins.js)
Got exception.

Event:      uncaught exception
cypress_runner.js:194616 Caught by:  "error" handler
cypress_runner.js:194616 Error:      TypeError: Cannot read properties of null (reading 'getRootNode')
    at handleDragStart (pointerAction.js:399:41)
    at handleMouseMoveMaybeDragStart (pointerAction.js:364:13)

```
   function handleMouseMoveMaybeDragStart(e) {
        e.preventDefault();
        const c = e.touches ? e.touches[0] : e;
        currentMousePosition = {x: c.clientX, y: c.clientY};
        if (
            Math.abs(currentMousePosition.x - dragStartMousePosition.x) >= MIN_MOVEMENT_BEFORE_DRAG_START_PX ||
            Math.abs(currentMousePosition.y - dragStartMousePosition.y) >= MIN_MOVEMENT_BEFORE_DRAG_START_PX
        ) {
            removeMaybeListeners();
            handleDragStart();
        }
    }
 ```

Not sure why it happened exactly, there's no other output. It works in general in the app. But with chaos testing it gives sometimes random errors in pointerActions.js

**Comment by isaacHagoel** [comment]
Can you test it again with the latest version?
I believe it is complaining about this line rather than the code snippet
you pasted.
https://github.com/isaacHagoel/svelte-dnd-action/blob/83f152f3faa17a80106905c972d27a8347a3575e/src/pointerAction.js#L388

From looking at the code I don't know how this error could be possible
unless it is a browser bug but maybe there is something I am missing
