### ISSUE TITLE
Detect if dragged item is dropped to original position

### ISSUE THREAD

**Issue by vhochstein** [isaacHagoel/svelte-dnd-action#587]
Hi,

I am storing order of records in a database and in case dragged item is dropped back to original position, it does nt make sense to call Database at all.

What s the best way to detect that in finalize ?

Thanks a lot for your support in advance.
--
Volker

**Comment by isaacHagoel** [comment]
Hello,
One way of doing it:
In the consider handler you can you check the "trigger" property (`e.detail.info.trigger`) and if it is TRIGGERS.DRAG_STARTED you can store the index of the dragged element before changing you `items`. The id of the dragged element is also available in `e.detail.info.id`. 
In the finalize handler if the trigger is  DROPPED_OUTSIDE_OF_ANY (which means the item returns to its original place in the original zone) you know for sure the item returned to its original index and no need to update the DB, if the trigger is DROPPED_INTO_ZONE and you have the original index stored (meaning it was dropped into the same zone, if it is the dropped into another zone that zone didn't store the index because it never got the DRAG_STARTED event) compare the new index (findIndex in e.detail.items) to the original one to decide whether you need to do anything. Don't forget to clear the index at the end.

Makes sense?

**Comment by isaacHagoel** [comment]
closing the issue cause i haven't heard back. if you still need help or want to me to create a code example pls let me know.

**Comment by vhochstein** [comment]
No that s fine, thanks a lot for your support

**Comment by vhochstein** [comment]
but maybe it would be great to add this to the existing example showing server side integration, cause I think it should be the common pattern to only push changes to server is there was a change
