### ISSUE TITLE
Disable / Pause dragging functionality

### ISSUE THREAD

**Issue by farskid** [isaacHagoel/svelte-dnd-action#61]
Is there a way to programmatically disable or pause the dragging functionality? 

Tried passing `null` as the value for `use:dndzone` to signal svelte to ignore this attribute but it's not working.

```
use:dndzone={isDragEnabled ? { items: column.items, FLIP_DURATION_MS } : null}
```

**Comment by isaacHagoel** [comment]
It is not supported but can be added.
Can you tell me more about the use case or provide a more complete example (REPL)? what would cause isDragEnabled to change?
Have you tried using an #if :else block (not elegant I know but as a temporary workaround)?

**Comment by isaacHagoel** [comment]
@farskid see above

**Comment by isaacHagoel** [comment]
@farskid I've created issue #63, will it address your need?

**Comment by farskid** [comment]
@isaacHagoel Thanks for the fast reply :)

the case I need this in is 3 list of items like 3 columns of. trello board. you can drag cards between these 3 items. clicking on the cards will open a modal containing card details. the problem happens when the modal is open cause the cards are still draggable. from a usability point of view, it makes sense to disable or rather temporarily pause the dragging functionality while the modal is open and resume when it's closed. therefore the state of board of items stays intact while you're reading the details of an individual card.

I can also reproduce this in a REPL if there are still blurry parts of the logic :)

about #63 , I think it addresses my need pretty well 👍 also happy to contribute if you need an extra pair of hands.

**Comment by isaacHagoel** [comment]
@farskid thanks for providing more details!
I am assuming you don't want users to click buttons or type into inputs on the page while the modal is open so it is not only dragging that you need to prevent. Is this a fair assumption?

The common solution for this problem is to use an overlay which in fact nothing more than an HTML element (ex: div) that covers the entire page while the modal is open, effectively blocking any interaction with the page. I'm sure you've seen this pattern all over the internet. 
I've created an example for you [in the REPL](https://svelte.dev/repl/62f30f3d3ffa4879b0411ed92f77e0a8?version=3.22.3).
It doesn't include this library for simplicity but it will block dragging (which is based on mouse/touch events) just like it blocks everything else.

If I understand your use-case correctly, this is a better solution for you than #63. 
Please confirm or correct me.

Regarding contributing, an extra pair of hands is welcome. If there is anything specific you have in mind, please let me know.

**Comment by farskid** [comment]
@isaacHagoel actually yeah. the modal is the one coming from bootstrap so I assumed the backdrop is stopping any events from propagating and therefore, drag would have been automatically disabled since you couldn't access the card element.
But for some reason, when the modal was open, you could drag the whole backdrop!

So by digging more I realized the reason for this strange behaviour was that the modal element was rendered inside the card element so it actually made sense! the library was doing it's job.

Bringing the modal element out of cards and making a shared one across all cards solved the problem.

anyways, I guess still having disabling and enabling programatically is a nice to have feature nonetheless.

**Comment by isaacHagoel** [comment]
@farskid I agree it is a nice feature!
I am just trying to find the proper way to do it (== the one that solves the largest amount of real world problems in the most elegant way) before I jump into coding it. 
I am discussing it on #62 as well (trying to uncover how this is going to be used)

**Comment by farskid** [comment]
I'll be closing this as it's resolved in https://github.com/isaacHagoel/svelte-dnd-action/issues/61#issuecomment-633307426.
