### ISSUE TITLE
Nested container quick drag/drop bug

### ISSUE THREAD

**Issue by benkuper** [isaacHagoel/svelte-dnd-action#614]
Hello, and thank you for this wonderful lib ! Tried many others and came back to this one :)

I have one struggle with nested containers. I understand there are some SHADOW parameters to help with this but even the crazy nesting REPL on the readme has this bug I believe :

https://svelte.dev/playground/fe8c9eca04f9417a94a8b6041df77139?version=3.59.2

When dragging a container containing other things, I have this problem where the consider() is triggered with the shadow item. However, even filtering this leads to the container being removed if my motion is too quick (less than half a second, just drag-release instantly).

This does not happen on "final" elements that don't contain any draggable child.

Here is the problem on my setup :

![ezgif-1-465c893c7d](https://github.com/user-attachments/assets/95201965-4188-423e-b6df-a05d65842db2)

**Comment by isaacHagoel** [comment]
I tried to reproduce with crazy nesting and couldn't. Would be awesome if you could provide accurate instructions.
That example does not use the data attribute etc that solve nesting conflicts (because it seemed like it didn't need it so I didn't add).
Have you seen the "Nested Zones Optional Optimization" section in the README? Can you try it?
If the problem persist can you please provide a REPL for me to debug?

**Comment by benkuper** [comment]
I had not seen this particular section indeed, works perfectly ! I still have some odd behaviours when dragging but that's not related to this problem, thank you !
