### ISSUE TITLE
example for limit items number ?

### ISSUE THREAD

**Issue by zba** [isaacHagoel/svelte-dnd-action#62]
I have list of variants and placeholders for answer in test, so in placeholders I need only one item possible, tried to check items.length in handleDndConsider, but never success. Any way to do this ?

**Comment by isaacHagoel** [comment]
Not sure I fully understand.
Do you need to make the dnd-zone allow taking items items away but not adding new items once the list has reached a certain maximum length?

**Comment by isaacHagoel** [comment]
@zba see above

**Comment by zba** [comment]
No, I want dnd zone which can contain only one item, it empty by default, but if there is value  you should not able to add new one, only drag out of it.

**Comment by isaacHagoel** [comment]
@zba thanks. I've created issue #63, will it address your need?
You should be able to do the following once you have it. 
Create a variable in your component `dropDisabled` and pass it into the dndzone.
On your `finalize` event handler, set it to true if items.length === 1, set it to false if items.length===0. 
If that will work for you, I can probably get in within the next few days.
I am open to other suggestions.

**Comment by zba** [comment]
It enough for my current task, but I think it is better to have such controls in handlers, because rules can be really complex, like accept only special items (fir example only correct answer), so better if it can be event method instead of directive.

**Comment by isaacHagoel** [comment]
@zba thanks for brainstorming this with me and please feel free to make a PR. Code speaks clearer that words. In general contributions are welcome and appreciated!

Adding the controls to the handlers seems potentially problematic to me in two ways:
1. *Technical*: preventDefault tells handlers that are **downstream** from the current one (ex: the browser itself) not to not act on the event (in case of the browser, it ignores custom events anyway, unlike the built-in event). In our case your component's event handler is **upstream** from the library, as in, the library tells your component about something that already happened (ex: the user dropped the element/ the element entered your zone). In order for a handlers based solution to work, the library will have also be upstream from your component, maybe by listening on its own custom events (consider and finalize) at the window level and only take action once it intercepts them there and check whether default was prevented or not (read: asynchrony). Maybe it is technically possible but I think it will be quite complicated to handle. For example: if the user dropped and element in a container but the container prevented-default, the library should probably try to put it back in the origin container but that one might preventDefault as well and then what?  When starting to drag an item (which could also be blocked I guess so it can't start until it gets confirmation from the upstream handler), the library highlights all of the possible drop zones, if any of them can deny drop arbitrarily, the library cannot do it anymore. I do think it is an interesting approach but I hope I illustrated some of my concerns. 
2.  *Semantic*: Svelte actions operate by taking an options object as input and emitting events as output. This is idiomatic Svelte and it creates a clear data flow (svelte-dnd-action uses it to create a cyclic feedback loop as it takes the items it had outputted back as input from the component after the component updated itself). 

In regards to complex rules, can you provide a more detailed example? I am really interested in discovering real-world cases in which the library is not flexible enough. For the one you've provided: accept only special items, isn't this addressed by the "type" option and/or the ability to handle 'finalize' in any way you'd like?
If your intention is that the user can drag from a container of multiple possible answers but only be allowed to drop the correct one in the target zone, isn't it better if you allow them to drop any answer but show a message when they drops the wrong one (and then reset if u want by resetting the items lists in both zones) rather than mysteriously not allowing the drop?

**Comment by zba** [comment]
example 

```
	function handleDndConsider(e) {
                        e.detail.items.find(item => item.result !=== task.result) {
                             return e.cancel();
                        }

			items = e.detail.items;
	}
```

or may be just make it possible to have a function before those handlers (as we don't have multitouch) , like: 

```
<script>
const allowedResult = 5;
function dropAllowed(item) {
    return (item.detail.result === 5)
}
</script>


<section use:dndzone={{items, dragDisabled:true, dropAllowed: dropAllowed}} on:consider=... on:finalize=...>
    ...
</section>
```

**Comment by isaacHagoel** [comment]
1. Thanks and sorry, I meant an example for a special case in which the current capabilities + #63 won't be sufficient not an example for canceling an event (same technical/ semantic issues as preventDefault). Can you please provide? 
2. Isn't running a function that returns a boolean actually weaker than passing the result of the function as an option like #63 suggests? 
Remember that you can update the options at any time and in any way you want, using the function that you showed above but you have full control over the timing (because you invoke it and not the library)

**Comment by zba** [comment]
1. This is example to show limitation of directive, because sometime you need to decide if you accept or not the items.
2. What you mean by weaker ? Boolean attribute, can be considered only for future drops, while function can consider current dragged item.

Btw, no problem with preventDefault(), because event handlers running synchronous in browser.I tried something, but because of mutationof items, it not work as expected for more than 1 item.

**Comment by isaacHagoel** [comment]
1. This not what I mean when i say 'example'. This is an arbitrary line of code. I mean a real world scenario, a use-case. If you tried to illustrate the "allow dropping only correct answer" scenario, I addressed it above. In short I think it is wrong for the library to reject the drop in that case (the app should tell the user the answer is wrong and then reset the state, this can all be done in the 'finalize' handler and is app responsibility, not the library's).
2. As I said above - if you pass in a callback, you can't control when your function is called, the library does. I also addressed the idea of affecting something that happened in the past and pointed to issues with it.

The browser ignores preventDefault for customEvents. I mentioned that above as well. I also outlined what the library will need to do in order to support this.

I am getting the feeling we don't communicate with each other very effectively.
Maybe there is something I am missing here.

**Comment by zba** [comment]
Make custom event cancelable: true, check event.defaultPrevented, will show you my current status, when get a time

**Comment by isaacHagoel** [comment]
That's what I said above that the library will have to listen to the event upstream to check whether default was prevented. Please read again.

**Comment by zba** [comment]
You not need to listen, event handlers running synchronous, you can read this property on next line after emit.

**Comment by zba** [comment]
In real world scenario, I need limit for test answers eq 1, and I though i can control it inside consider handler, which is natural for js :) but wasn't able :)   

If little extend my task to accept only "correct" answer in placeholder, I would to be able to run a function which can decide if the answer correct or not, because it may require some simple calculations which can't be applied using type or boolean attribute. I believe, that your users will be happy to able to control their components much more, than accept all items which was sent by finalize event :)

**Comment by isaacHagoel** [comment]
Okay. You pointed out to a wrong assumption I was making about events. Thank you sir! 
I ran this little test and although defaultPrevented doesn't updated for the next line, I can indeed check whether the event was cancelled by looking at the value returned from dispatchEvent (I didn't know that).
https://svelte.dev/repl/48f3a06eb65549a0aaeaf1b4d9e4576f?version=3.22.3

That means that technically, this option is not as complex as I thought.
I will give it more thought on the semantic side.
Thanks for the input. I've learnt something new.

**Comment by isaacHagoel** [comment]
@zba (followup on the comment above):
placed some thoughts in #63
