### ISSUE TITLE
Customize the dropzone style?

### ISSUE THREAD

**Issue by nathancahill** [isaacHagoel/svelte-dnd-action#81]
Right now the style is hardcoded as `dz.style.outline = 'rgba(255, 255, 102, 0.7) solid 2px'`

Would you be interested in a PR that customizes that style?

**Comment by isaacHagoel** [comment]
Sure. My thinking was to keep things as simple as possible and add customisation options as needs arise 
Do you have something specific in mind (API)?

**Comment by nathancahill** [comment]
This is the idea: https://github.com/isaacHagoel/svelte-dnd-action/compare/master...nathancahill:master

**Comment by nathancahill** [comment]
Basically: 

```js
use:dndzone={{items, activeStyle: { outline: 'rgba(255, 255, 102, 0.7) solid 2px' } }}
```

**Comment by isaacHagoel** [comment]
The code looks legit! nice work sir.
I do have 4 comments:

1. JSDoc will need to have the extra param added (easy)
2. README.md should include the new option
3. I wonder whether there is a clearer name (from the user perspective) than 'activeStyle' for the option... not sure there is tbh, raising it anyway
4. Removing the active styles might need to be more sophisticated. I thought I could get away with setting the outline property to '' because it is rarely used. What if we set background or border to ''? That might result in unexpected behaviour if there was another value there before. Do you think we should backup the original values and restore them? Alternatively we should be explicit about this in the README

**Comment by nathancahill** [comment]
3. Yes, the name can be better. Maybe `considerStyle`? `active` is vague.
 
4. The styles are only being removed if applied directly to the element with the inline styles tag. It's not wiping styles applied Svelte's `<style>` or anything else. Still better to backup and restore.

Adding a fifth item as I've been playing with the code more:

5. The `dzToConfig` logic means that dropzones are getting styled with the config from the dropzone the item is being dragged *from*, this might be different. I'll try to fix that today.

**Comment by isaacHagoel** [comment]
3. it doesn't trigger on consider but when an element from the same type is being dragged around. Maybe something like "dropTargetStyle" or "activeDropTargetStyle"?
4. You are right. I am aware. If backing up is too tricky it is okay to not do it as long as we are explicit about it in the README (we can improve it later + it is a user defined option)
5. Good point! Each dz should be styled based on its own config.  

Adding 6:
Should the existence of this option cancel the default highlighting or add to it?

**Comment by PlkMarudny** [comment]
This somehow does not work as expected, I mean the default highlighting should be replaced, otherwise the first highlight displays the ugly yellow outline (but is seems it does not). What is even worse, each dnd source applies the yellow outline separately on first dnd operation.

**Comment by isaacHagoel** [comment]
@PlkMarudny not sure I follow. Please provide more details and a REPL demonstrating the issue.

**Comment by PlkMarudny** [comment]
I am sorry, my mistake, it is working actually as expected.
