### ISSUE TITLE
Custom drag handles

### ISSUE THREAD

**Issue by vc-ca** [isaacHagoel/svelte-dnd-action#86]
I only want a specific area inside of a list item to be draggable. Is this possible with Svelte DND Action?

Link to [React DND custom drag handle example.](https://egghead.io/lessons/react-designate-control-of-dragging-for-a-react-beautiful-dnd-draggable-with-draghandleprops)

**Comment by isaacHagoel** [comment]
there is no support for drag handles at the moment.
it shouldn't be super difficult to add it though. It would involve attaching the mousedown/touchstart listeners to the handle instead of the entire element. Other than that, the main challenge is coming up with a good API (as in how do we tell the library what the drag handle is), proper error handling and dealing with config changes on the fly (as in, the programmer enables/ disables the handle option after initialisation).
If you'd like to take it on and work towards a pull request I am more than happy to brainstorm the API and guide you through it. Otherwise, I will look into it when I have a bit more spare time again.

**Comment by vc-ca** [comment]
Understood, Thanks for the followup! 👍

**Comment by isaacHagoel** [comment]
Actually, I had a eureka moment about this. This is almost fully supported right now with only two lines of css.
See [this REPL](https://svelte.dev/repl/30c2fdad546346de88105011012fe1d7?version=3)

The only missing bit is not disabling user-select in such a case. This should be tiny to implement. I just need to think what's the best API to create for this (maybe i will go with some kind of 'handle' api that will apply the css in the example behind the scenes). 

FYI @zahachtah

**Comment by zahachtah** [comment]
That's more than awesome! will implement it right away!

**Comment by gleuch** [comment]
For those needing an example for using a custom drag handle, [check out this REPL](https://svelte.dev/repl/a95219b1ff474119bb42e90fe1df7557?version=3.24.1).

**Comment by isaacHagoel** [comment]
@gleuch 
Haha. Nice! Thanks for that.
You worked around the user-select issue by enabling drag on mouse down on the handle, and disabling on mouse up.
One issue with the example as-is is that it won't support touch screens but that should be easy to fix (adding touchstart and touchend listeners). 
I am currently working on adding some examples to the README. I will include this one for sure.

@vc-ca @zahachtah is this solution good enough for you? if so, I would rather not increasing the footprint of the library.

**Comment by vc-ca** [comment]
Works for me, ya'll are awesome! <br>
![Alt Text](https://media.giphy.com/media/5xaOcLDE64VMF4LqqrK/giphy.gif)

**Comment by vc-ca** [comment]
@gleuch 's solution works great on a desktop, but for some reason, it's laggy (for me at least) when viewed on a phone. 

I thought it might have something to do with the $: reactive statement? So I took that out, used standard functions and am still getting poor performance on a phone. See [this repl](https://svelte.dev/repl/7eb1fe7730394d9397700ef294d805aa?version=3.28.0)

In contrast, I have no performance issues with the standard Svelte DND Action package while using a phone. 

Thoughts? Thanks

**Comment by isaacHagoel** [comment]
@vc-ca nice catch. It is because of a missing `e.preventDefault()` on touchstart (which allows the browser to scroll the screen as you drag and causes a lag).
I added the fix to the [repl that is linked from the README](https://svelte.dev/repl/4949485c5a8f46e7bdbeb73ed565a9c7?version=3.24.1). Give it a shot.

**Comment by vc-ca** [comment]
That did it, thanks for the quick assistance!

**Comment by isaacHagoel** [comment]
Just FYI, I updated the [drag handles example](https://svelte.dev/repl/4949485c5a8f46e7bdbeb73ed565a9c7?version=3.29.0) to also work for keyboard drag and drop (plus cleaned it up a bit)
