### ISSUE TITLE
I would like an option to specify the name of the id

### ISSUE THREAD

**Issue by erikbent** [isaacHagoel/svelte-dnd-action#90]
I am using PouchDB with svelte and an item in PouchDB uses _id as the unique identifier. I would like an option to define the name of the id.

**Comment by isaacHagoel** [comment]
Hi,
so within the items array you want to pass in something like
```
items = [{_id:1, text:"item1"},  {_id:2, text:"item2"}]
```
?
and you would want to pass in the id name as a param?
something like:
```
<section use:dndzone={{items, keyName: '_id'}}
```

**Comment by tohodakilla** [comment]
that would be awesome, it could work with mongoDB ids format out of the box.

**Comment by isaacHagoel** [comment]
this should be the next one on my list :)

**Comment by isaacHagoel** [comment]
Hi @erikbent , @tohodakilla ,
Please have a look at PR #122.
I realised the `id` key-name can only be overridden globally and not at the individual zone level. That's because items can be moved between dropzones and need to be able to rely on a common key property. 
With that said, **I think the solution I came up with addresses your need**, plus it protects people from doing anything that could backfire. 
I would appreciate it if you could look at the PR (the README explains how to use the new feature) and let me know whether this works for you.

**Comment by tohodakilla** [comment]
@isaacHagoel It looks great! I think there is no need for different id for different zones. Global change is exactly what is needed in order to work with data from mongoDB / PouchDB out of the box.

I have read README from PR and it makes perfect sense 👍 
<3

**Comment by isaacHagoel** [comment]
@tohodakilla thanks for the feedback. merged

**Comment by erikbent** [comment]
Sorry that didn't replied (I was on vacation). This looks great. Thanks.

Op wo 16 sep. 2020 om 00:33 schreef Isaac Hagoel <notifications@github.com>:
