### ISSUE TITLE
Experiment: avoid state changes during flip animation

### ISSUE THREAD

**Issue by isaacHagoel** [isaacHagoel/svelte-dnd-action#94]
see [this comment](https://github.com/isaacHagoel/svelte-dnd-action/issues/91#issuecomment-663922073) and the thread leading to it for details.

**Comment by isaacHagoel** [comment]
I have created a simple implementation of this but I still occasionally get "Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node'"
Potentially useful links for further research:
https://github.com/SortableJS/react-sortablejs/issues/19
https://github.com/facebook/react/issues/8025

**Comment by jlkiri** [comment]
Not sure that it can help, but here's my experiment with spring animations and WAAPI. It's framework agnostic, so probably can be used with with lib, but since mounts and unmounts are involved, it needs a little bit more work. Overall it should be very performant.

https://www.kirillvasiltsov.com/writing/post/how-to-create-a-spring-animation-with-web-animation-api

**Comment by isaacHagoel** [comment]
cool writeup. not sure it helps but still cool to read :)
this issue is at the top of my list. i want to really get to the bottom of it and understand what's up before jumping into a solution.

**Comment by isaacHagoel** [comment]
closing this. I cannot get this exception anymore with 0.2.9 (which makes sense considering the fix it introduced)
